### ISSUE TITLE
As a user, I want to use a "global modifier" to apply modifiers to my roll

### ISSUE THREAD

**Issue by Razortide** [Brownie79/fvtt-swade-tokenbar#2]
Hello Dev,

just a suggestion: I would love to have a "global modifier" field that defaults to "0". By hovering over the field and using the mousewheel I can add/subtract to that value by +1/-1 steps.
When rolling a skill/attribute/anything (except maybe non-replenishing tables) I want to apply that modifier to my roll and reset the value to 0 (ready for the next roll.

**Comment by Razortide** [comment]
I was just thinking:
How about this: When you open the Attributes or Skills Tab, you can hover over a certain skill or attribute and mousewheel directly on it. If you do, it would be like "NAME (MODIFIER)" until you either roll or hover away. I thought this would be even more convenient since you have everything in one place?

Best regards,
Marc

**Comment by spacemandev-git** [comment]
added text box for modifier. the hover stuff is hard cause i don't know how to add scroll events to that.
check out 1.1 for the modifier box
