### ISSUE TITLE
Attribute and Skill rolls not working...

### ISSUE THREAD

**Issue by WildBillLives** [Brownie79/fvtt-swade-tokenbar#4]
I'm new to running SWADE on Foundry, but I just installed the SWADE world and the SWADE Token Bar, and neither the attribute nor skill rolls will work from the bar. I get the following error message in the browser console:

dropdown.js:77 Uncaught (in promise) TypeError: actor.calcWoundFatigePenalties is not a function
    at handleEvent (dropdown.js:77)
    at HTMLBodyElement.<anonymous> (dropdown.js:61)
    at HTMLBodyElement.dispatch (jquery.min.js:2)
    at HTMLBodyElement.v.handle (jquery.min.js:2)

I am using the latest version of the tool bar and the SWADE world that is available on The Forge (where the game is running).

**Comment by spacemandev-git** [comment]
what version of SWADE Token Bar are you on? This should be fixed in v1.1
